package v20241105

type Definitions struct {
	Annotated                       Annotated                   `json:"Annotated"`
	BlobResourceContents            BlobResourceContents        `json:"BlobResourceContents"`
	CallToolRequest                 CallToolRequest             `json:"CallToolRequest"`
	CallToolResult                  CallToolResult              `json:"CallToolResult"`
	CancelledNotification           CancelledNotification       `json:"CancelledNotification"`
	ClientCapabilities              ClientCapabilities          `json:"ClientCapabilities"`
	ClientNotification              ClientNotification          `json:"ClientNotification"`
	ClientRequest                   ClientNotification          `json:"ClientRequest"`
	ClientResult                    ClientNotification          `json:"ClientResult"`
	CompleteRequest                 CompleteRequest             `json:"CompleteRequest"`
	CompleteResult                  CompleteResult              `json:"CompleteResult"`
	CreateMessageRequest            CreateMessageRequest        `json:"CreateMessageRequest"`
	CreateMessageResult             CreateMessageResult         `json:"CreateMessageResult"`
	Cursor                          Cursor                      `json:"Cursor"`
	EmbeddedResource                EmbeddedResource            `json:"EmbeddedResource"`
	EmptyResult                     EmptyResult                 `json:"EmptyResult"`
	GetPromptRequest                GetPromptRequest            `json:"GetPromptRequest"`
	GetPromptResult                 GetPromptResult             `json:"GetPromptResult"`
	ImageContent                    ImageContent                `json:"ImageContent"`
	Implementation                  Implementation              `json:"Implementation"`
	InitializeRequest               InitializeRequest           `json:"InitializeRequest"`
	InitializeResult                InitializeResult            `json:"InitializeResult"`
	InitializedNotification         EdNotification              `json:"InitializedNotification"`
	JSONRPCError                    JSONRPCError                `json:"JSONRPCError"`
	JSONRPCMessage                  ClientNotification          `json:"JSONRPCMessage"`
	JSONRPCNotification             JSONRPCNotification         `json:"JSONRPCNotification"`
	JSONRPCRequest                  JSONRPCRequest              `json:"JSONRPCRequest"`
	JSONRPCResponse                 JSONRPCResponse             `json:"JSONRPCResponse"`
	ListPromptsRequest              ListSRequest                `json:"ListPromptsRequest"`
	ListPromptsResult               ListPromptsResult           `json:"ListPromptsResult"`
	ListResourceTemplatesRequest    ListSRequest                `json:"ListResourceTemplatesRequest"`
	ListResourceTemplatesResult     ListResourceTemplatesResult `json:"ListResourceTemplatesResult"`
	ListResourcesRequest            ListSRequest                `json:"ListResourcesRequest"`
	ListResourcesResult             ListResourcesResult         `json:"ListResourcesResult"`
	ListRootsRequest                Request                     `json:"ListRootsRequest"`
	ListRootsResult                 ListRootsResult             `json:"ListRootsResult"`
	ListToolsRequest                ListSRequest                `json:"ListToolsRequest"`
	ListToolsResult                 ListToolsResult             `json:"ListToolsResult"`
	LoggingLevel                    LoggingLevel                `json:"LoggingLevel"`
	LoggingMessageNotification      LoggingMessageNotification  `json:"LoggingMessageNotification"`
	ModelHint                       ModelHint                   `json:"ModelHint"`
	ModelPreferences                ModelPreferences            `json:"ModelPreferences"`
	Notification                    Notification                `json:"Notification"`
	PaginatedRequest                PaginatedRequest            `json:"PaginatedRequest"`
	PaginatedResult                 PaginatedResult             `json:"PaginatedResult"`
	PingRequest                     Request                     `json:"PingRequest"`
	ProgressNotification            ProgressNotification        `json:"ProgressNotification"`
	ProgressToken                   ProgressToken               `json:"ProgressToken"`
	Prompt                          Prompt                      `json:"Prompt"`
	PromptArgument                  PromptArgument              `json:"PromptArgument"`
	PromptListChangedNotification   EdNotification              `json:"PromptListChangedNotification"`
	PromptMessage                   Message                     `json:"PromptMessage"`
	PromptReference                 PromptReference             `json:"PromptReference"`
	ReadResourceRequest             ReadResourceRequest         `json:"ReadResourceRequest"`
	ReadResourceResult              ReadResourceResult          `json:"ReadResourceResult"`
	Request                         RequestClass                `json:"Request"`
	RequestID                       ProgressToken               `json:"RequestId"`
	Resource                        Resource                    `json:"Resource"`
	ResourceContents                ResourceContents            `json:"ResourceContents"`
	ResourceListChangedNotification EdNotification              `json:"ResourceListChangedNotification"`
	ResourceReference               ResourceReference           `json:"ResourceReference"`
	ResourceTemplate                ResourceTemplate            `json:"ResourceTemplate"`
	ResourceUpdatedNotification     ReadResourceRequest         `json:"ResourceUpdatedNotification"`
	Result                          Result                      `json:"Result"`
	Role                            LoggingLevel                `json:"Role"`
	Root                            Root                        `json:"Root"`
	RootsListChangedNotification    EdNotification              `json:"RootsListChangedNotification"`
	SamplingMessage                 Message                     `json:"SamplingMessage"`
	ServerCapabilities              ServerCapabilities          `json:"ServerCapabilities"`
	ServerNotification              ClientNotification          `json:"ServerNotification"`
	ServerRequest                   ClientNotification          `json:"ServerRequest"`
	ServerResult                    ClientNotification          `json:"ServerResult"`
	SetLevelRequest                 SetLevelRequest             `json:"SetLevelRequest"`
	SubscribeRequest                ReadResourceRequest         `json:"SubscribeRequest"`
	TextContent                     TextContent                 `json:"TextContent"`
	TextResourceContents            TextResourceContents        `json:"TextResourceContents"`
	Tool                            Tool                        `json:"Tool"`
	ToolListChangedNotification     EdNotification              `json:"ToolListChangedNotification"`
	UnsubscribeRequest              ReadResourceRequest         `json:"UnsubscribeRequest"`
}
