package vdraft

type Definitions struct {
	Annotations                       Annotations                      `json:"Annotations"`
	AudioContent                      Content                          `json:"AudioContent"`
	BaseMetadata                      BaseMetadata                     `json:"BaseMetadata"`
	BlobResourceContents              ResourceContents                 `json:"BlobResourceContents"`
	BooleanSchema                     BooleanSchema                    `json:"BooleanSchema"`
	CallToolRequest                   CallToolRequest                  `json:"CallToolRequest"`
	CallToolRequestParams             RequestParams                    `json:"CallToolRequestParams"`
	CallToolResult                    CallToolResult                   `json:"CallToolResult"`
	CancelledNotification             CallToolRequest                  `json:"CancelledNotification"`
	CancelledNotificationParams       CancelledNotificationParams      `json:"CancelledNotificationParams"`
	ClientCapabilities                ClientCapabilities               `json:"ClientCapabilities"`
	ClientNotification                ClientNotification               `json:"ClientNotification"`
	ClientRequest                     ClientNotification               `json:"ClientRequest"`
	ClientResult                      ClientNotification               `json:"ClientResult"`
	CompleteRequest                   CallToolRequest                  `json:"CompleteRequest"`
	CompleteRequestParams             CompleteRequestParams            `json:"CompleteRequestParams"`
	CompleteResult                    CompleteResult                   `json:"CompleteResult"`
	ContentBlock                      ClientNotification               `json:"ContentBlock"`
	CreateMessageRequest              CallToolRequest                  `json:"CreateMessageRequest"`
	CreateMessageRequestParams        CreateMessageRequestParams       `json:"CreateMessageRequestParams"`
	CreateMessageResult               CreateMessageResult              `json:"CreateMessageResult"`
	Cursor                            Cursor                           `json:"Cursor"`
	ElicitRequest                     CallToolRequest                  `json:"ElicitRequest"`
	ElicitRequestParams               ElicitRequestParams              `json:"ElicitRequestParams"`
	ElicitResult                      ElicitResult                     `json:"ElicitResult"`
	EmbeddedResource                  EmbeddedResource                 `json:"EmbeddedResource"`
	EmptyResult                       EmptyResult                      `json:"EmptyResult"`
	EnumSchema                        EnumSchema                       `json:"EnumSchema"`
	Error                             Error                            `json:"Error"`
	GetPromptRequest                  CallToolRequest                  `json:"GetPromptRequest"`
	GetPromptRequestParams            RequestParams                    `json:"GetPromptRequestParams"`
	GetPromptResult                   GetPromptResult                  `json:"GetPromptResult"`
	Icon                              Icon                             `json:"Icon"`
	Icons                             Icons                            `json:"Icons"`
	ImageContent                      Content                          `json:"ImageContent"`
	Implementation                    Implementation                   `json:"Implementation"`
	InitializeRequest                 CallToolRequest                  `json:"InitializeRequest"`
	InitializeRequestParams           InitializeRequestParams          `json:"InitializeRequestParams"`
	InitializeResult                  InitializeResult                 `json:"InitializeResult"`
	InitializedNotification           CallToolRequest                  `json:"InitializedNotification"`
	JSONRPCError                      JSONRPCError                     `json:"JSONRPCError"`
	JSONRPCMessage                    JsonrpcMessage                   `json:"JSONRPCMessage"`
	JSONRPCNotification               JSONRPCNotificationClass         `json:"JSONRPCNotification"`
	JSONRPCRequest                    JSONRPCNotificationClass         `json:"JSONRPCRequest"`
	JSONRPCResponse                   JSONRPCResponse                  `json:"JSONRPCResponse"`
	ListPromptsRequest                CallToolRequest                  `json:"ListPromptsRequest"`
	ListPromptsResult                 ListPromptsResult                `json:"ListPromptsResult"`
	ListResourceTemplatesRequest      CallToolRequest                  `json:"ListResourceTemplatesRequest"`
	ListResourceTemplatesResult       ListResourceTemplatesResult      `json:"ListResourceTemplatesResult"`
	ListResourcesRequest              CallToolRequest                  `json:"ListResourcesRequest"`
	ListResourcesResult               ListResourcesResult              `json:"ListResourcesResult"`
	ListRootsRequest                  CallToolRequest                  `json:"ListRootsRequest"`
	ListRootsResult                   ListRootsResult                  `json:"ListRootsResult"`
	ListToolsRequest                  CallToolRequest                  `json:"ListToolsRequest"`
	ListToolsResult                   ListToolsResult                  `json:"ListToolsResult"`
	LoggingLevel                      LoggingLevel                     `json:"LoggingLevel"`
	LoggingMessageNotification        CallToolRequest                  `json:"LoggingMessageNotification"`
	LoggingMessageNotificationParams  LoggingMessageNotificationParams `json:"LoggingMessageNotificationParams"`
	ModelHint                         ModelHint                        `json:"ModelHint"`
	ModelPreferences                  ModelPreferences                 `json:"ModelPreferences"`
	Notification                      Notification                     `json:"Notification"`
	NotificationParams                NotificationParams               `json:"NotificationParams"`
	NumberSchema                      NumberSchema                     `json:"NumberSchema"`
	PaginatedRequest                  PaginatedRequest                 `json:"PaginatedRequest"`
	PaginatedRequestParams            PaginatedRequestParams           `json:"PaginatedRequestParams"`
	PaginatedResult                   PaginatedResult                  `json:"PaginatedResult"`
	PingRequest                       CallToolRequest                  `json:"PingRequest"`
	PrimitiveSchemaDefinition         JsonrpcMessage                   `json:"PrimitiveSchemaDefinition"`
	ProgressNotification              CallToolRequest                  `json:"ProgressNotification"`
	ProgressNotificationParams        ProgressNotificationParams       `json:"ProgressNotificationParams"`
	ProgressToken                     ProgressToken                    `json:"ProgressToken"`
	Prompt                            Prompt                           `json:"Prompt"`
	PromptArgument                    PromptArgument                   `json:"PromptArgument"`
	PromptListChangedNotification     CallToolRequest                  `json:"PromptListChangedNotification"`
	PromptMessage                     PromptMessage                    `json:"PromptMessage"`
	PromptReference                   PromptReference                  `json:"PromptReference"`
	ReadResourceRequest               CallToolRequest                  `json:"ReadResourceRequest"`
	ReadResourceRequestParams         ReadResourceRequestParamsClass   `json:"ReadResourceRequestParams"`
	ReadResourceResult                ReadResourceResult               `json:"ReadResourceResult"`
	Request                           Notification                     `json:"Request"`
	RequestID                         ProgressToken                    `json:"RequestId"`
	RequestParams                     RequestParamsClass               `json:"RequestParams"`
	Resource                          Resource                         `json:"Resource"`
	ResourceContents                  ResourceContentsClass            `json:"ResourceContents"`
	ResourceLink                      Resource                         `json:"ResourceLink"`
	ResourceListChangedNotification   CallToolRequest                  `json:"ResourceListChangedNotification"`
	ResourceRequestParams             ReadResourceRequestParamsClass   `json:"ResourceRequestParams"`
	ResourceTemplate                  Resource                         `json:"ResourceTemplate"`
	ResourceTemplateReference         ResourceTemplateReference        `json:"ResourceTemplateReference"`
	ResourceUpdatedNotification       CallToolRequest                  `json:"ResourceUpdatedNotification"`
	ResourceUpdatedNotificationParams ReadResourceRequestParamsClass   `json:"ResourceUpdatedNotificationParams"`
	Result                            Result                           `json:"Result"`
	Role                              LoggingLevel                     `json:"Role"`
	Root                              Root                             `json:"Root"`
	RootsListChangedNotification      CallToolRequest                  `json:"RootsListChangedNotification"`
	SamplingMessage                   SamplingMessage                  `json:"SamplingMessage"`
	ServerCapabilities                ServerCapabilities               `json:"ServerCapabilities"`
	ServerNotification                ClientNotification               `json:"ServerNotification"`
	ServerRequest                     ClientNotification               `json:"ServerRequest"`
	ServerResult                      ClientNotification               `json:"ServerResult"`
	SetLevelRequest                   CallToolRequest                  `json:"SetLevelRequest"`
	SetLevelRequestParams             SetLevelRequestParams            `json:"SetLevelRequestParams"`
	StringSchema                      StringSchema                     `json:"StringSchema"`
	SubscribeRequest                  CallToolRequest                  `json:"SubscribeRequest"`
	SubscribeRequestParams            ReadResourceRequestParamsClass   `json:"SubscribeRequestParams"`
	TextContent                       EmbeddedResource                 `json:"TextContent"`
	TextResourceContents              ResourceContents                 `json:"TextResourceContents"`
	Tool                              Resource                         `json:"Tool"`
	ToolAnnotations                   ToolAnnotations                  `json:"ToolAnnotations"`
	ToolListChangedNotification       CallToolRequest                  `json:"ToolListChangedNotification"`
	UnsubscribeRequest                CallToolRequest                  `json:"UnsubscribeRequest"`
	UnsubscribeRequestParams          ReadResourceRequestParamsClass   `json:"UnsubscribeRequestParams"`
}
