package vdraft

type Defs struct {
	Annotations                       Annotations                      `json:"Annotations"`
	AudioContent                      Content                          `json:"AudioContent"`
	BaseMetadata                      BaseMetadata                     `json:"BaseMetadata"`
	BlobResourceContents              ResourceContents                 `json:"BlobResourceContents"`
	BooleanSchema                     BooleanSchema                    `json:"BooleanSchema"`
	CallToolRequest                   CallToolRequest                  `json:"CallToolRequest"`
	CallToolRequestParams             CallToolRequestParams            `json:"CallToolRequestParams"`
	CallToolResult                    CallToolResult                   `json:"CallToolResult"`
	CancelTaskRequest                 Request                          `json:"CancelTaskRequest"`
	CancelTaskResult                  CancelTaskResult                 `json:"CancelTaskResult"`
	CancelledNotification             CallToolRequest                  `json:"CancelledNotification"`
	CancelledNotificationParams       CancelledNotificationParams      `json:"CancelledNotificationParams"`
	ClientCapabilities                ClientCapabilities               `json:"ClientCapabilities"`
	ClientNotification                ClientNotification               `json:"ClientNotification"`
	ClientRequest                     ClientNotification               `json:"ClientRequest"`
	ClientResult                      Result                           `json:"ClientResult"`
	CompleteRequest                   CallToolRequest                  `json:"CompleteRequest"`
	CompleteRequestParams             CompleteRequestParams            `json:"CompleteRequestParams"`
	CompleteResult                    CompleteResult                   `json:"CompleteResult"`
	ContentBlock                      ClientNotification               `json:"ContentBlock"`
	CreateMessageRequest              CallToolRequest                  `json:"CreateMessageRequest"`
	CreateMessageRequestParams        CreateMessageRequestParams       `json:"CreateMessageRequestParams"`
	CreateMessageResult               CreateMessageResult              `json:"CreateMessageResult"`
	CreateTaskResult                  CreateTaskResult                 `json:"CreateTaskResult"`
	Cursor                            Cursor                           `json:"Cursor"`
	ElicitRequest                     CallToolRequest                  `json:"ElicitRequest"`
	ElicitRequestFormParams           ElicitRequestFormParams          `json:"ElicitRequestFormParams"`
	ElicitRequestParams               ElicitRequestParams              `json:"ElicitRequestParams"`
	ElicitRequestURLParams            ElicitRequestURLParams           `json:"ElicitRequestURLParams"`
	ElicitResult                      ElicitResult                     `json:"ElicitResult"`
	ElicitationCompleteNotification   ElicitationCompleteNotification  `json:"ElicitationCompleteNotification"`
	EmbeddedResource                  EmbeddedResource                 `json:"EmbeddedResource"`
	EmptyResult                       EmptyResult                      `json:"EmptyResult"`
	EnumSchema                        ClientNotification               `json:"EnumSchema"`
	Error                             Error                            `json:"Error"`
	GetPromptRequest                  CallToolRequest                  `json:"GetPromptRequest"`
	GetPromptRequestParams            GetPromptRequestParams           `json:"GetPromptRequestParams"`
	GetPromptResult                   GetPromptResult                  `json:"GetPromptResult"`
	GetTaskPayloadRequest             Request                          `json:"GetTaskPayloadRequest"`
	GetTaskPayloadResult              GetTaskPayloadResult             `json:"GetTaskPayloadResult"`
	GetTaskRequest                    Request                          `json:"GetTaskRequest"`
	GetTaskResult                     CancelTaskResult                 `json:"GetTaskResult"`
	Icon                              Icon                             `json:"Icon"`
	Icons                             Icons                            `json:"Icons"`
	ImageContent                      Content                          `json:"ImageContent"`
	Implementation                    Implementation                   `json:"Implementation"`
	InitializeRequest                 CallToolRequest                  `json:"InitializeRequest"`
	InitializeRequestParams           InitializeRequestParams          `json:"InitializeRequestParams"`
	InitializeResult                  InitializeResult                 `json:"InitializeResult"`
	InitializedNotification           CallToolRequest                  `json:"InitializedNotification"`
	JSONRPCErrorResponse              JSONRPCErrorResponse             `json:"JSONRPCErrorResponse"`
	JSONRPCMessage                    ElicitRequestParams              `json:"JSONRPCMessage"`
	JSONRPCNotification               JSONRPCNotificationClass         `json:"JSONRPCNotification"`
	JSONRPCRequest                    JSONRPCNotificationClass         `json:"JSONRPCRequest"`
	JSONRPCResponse                   ElicitRequestParams              `json:"JSONRPCResponse"`
	JSONRPCResultResponse             JSONRPCResultResponse            `json:"JSONRPCResultResponse"`
	LegacyTitledEnumSchema            LegacyTitledEnumSchema           `json:"LegacyTitledEnumSchema"`
	ListPromptsRequest                CallToolRequest                  `json:"ListPromptsRequest"`
	ListPromptsResult                 ListPromptsResult                `json:"ListPromptsResult"`
	ListResourceTemplatesRequest      CallToolRequest                  `json:"ListResourceTemplatesRequest"`
	ListResourceTemplatesResult       ListResourceTemplatesResult      `json:"ListResourceTemplatesResult"`
	ListResourcesRequest              CallToolRequest                  `json:"ListResourcesRequest"`
	ListResourcesResult               ListResourcesResult              `json:"ListResourcesResult"`
	ListRootsRequest                  CallToolRequest                  `json:"ListRootsRequest"`
	ListRootsResult                   ListRootsResult                  `json:"ListRootsResult"`
	ListTasksRequest                  CallToolRequest                  `json:"ListTasksRequest"`
	ListTasksResult                   ListTasksResult                  `json:"ListTasksResult"`
	ListToolsRequest                  CallToolRequest                  `json:"ListToolsRequest"`
	ListToolsResult                   ListToolsResult                  `json:"ListToolsResult"`
	LoggingLevel                      LoggingLevel                     `json:"LoggingLevel"`
	LoggingMessageNotification        CallToolRequest                  `json:"LoggingMessageNotification"`
	LoggingMessageNotificationParams  LoggingMessageNotificationParams `json:"LoggingMessageNotificationParams"`
	ModelHint                         ModelHint                        `json:"ModelHint"`
	ModelPreferences                  ModelPreferences                 `json:"ModelPreferences"`
	MultiSelectEnumSchema             ClientNotification               `json:"MultiSelectEnumSchema"`
	Notification                      Notification                     `json:"Notification"`
	NotificationParams                NotificationParams               `json:"NotificationParams"`
	NumberSchema                      NumberSchema                     `json:"NumberSchema"`
	PaginatedRequest                  PaginatedRequest                 `json:"PaginatedRequest"`
	PaginatedRequestParams            PaginatedRequestParams           `json:"PaginatedRequestParams"`
	PaginatedResult                   PaginatedResult                  `json:"PaginatedResult"`
	PingRequest                       CallToolRequest                  `json:"PingRequest"`
	PrimitiveSchemaDefinition         ElicitRequestParams              `json:"PrimitiveSchemaDefinition"`
	ProgressNotification              CallToolRequest                  `json:"ProgressNotification"`
	ProgressNotificationParams        ProgressNotificationParams       `json:"ProgressNotificationParams"`
	ProgressToken                     ProgressToken                    `json:"ProgressToken"`
	Prompt                            Prompt                           `json:"Prompt"`
	PromptArgument                    PromptArgument                   `json:"PromptArgument"`
	PromptListChangedNotification     CallToolRequest                  `json:"PromptListChangedNotification"`
	PromptMessage                     PromptMessage                    `json:"PromptMessage"`
	PromptReference                   PromptReference                  `json:"PromptReference"`
	ReadResourceRequest               CallToolRequest                  `json:"ReadResourceRequest"`
	ReadResourceRequestParams         ReadResourceRequestParamsClass   `json:"ReadResourceRequestParams"`
	ReadResourceResult                ReadResourceResult               `json:"ReadResourceResult"`
	RelatedTaskMetadata               RelatedTaskMetadata              `json:"RelatedTaskMetadata"`
	Request                           Notification                     `json:"Request"`
	RequestID                         ProgressToken                    `json:"RequestId"`
	RequestParams                     RequestParams                    `json:"RequestParams"`
	Resource                          Resource                         `json:"Resource"`
	ResourceContents                  ResourceContentsClass            `json:"ResourceContents"`
	ResourceLink                      Resource                         `json:"ResourceLink"`
	ResourceListChangedNotification   CallToolRequest                  `json:"ResourceListChangedNotification"`
	ResourceRequestParams             ReadResourceRequestParamsClass   `json:"ResourceRequestParams"`
	ResourceTemplate                  Resource                         `json:"ResourceTemplate"`
	ResourceTemplateReference         ResourceTemplateReference        `json:"ResourceTemplateReference"`
	ResourceUpdatedNotification       CallToolRequest                  `json:"ResourceUpdatedNotification"`
	ResourceUpdatedNotificationParams ReadResourceRequestParamsClass   `json:"ResourceUpdatedNotificationParams"`
	Result                            GetTaskPayloadResult             `json:"Result"`
	Role                              LoggingLevel                     `json:"Role"`
	Root                              Root                             `json:"Root"`
	RootsListChangedNotification      CallToolRequest                  `json:"RootsListChangedNotification"`
	SamplingMessage                   SamplingMessage                  `json:"SamplingMessage"`
	SamplingMessageContentBlock       ClientNotification               `json:"SamplingMessageContentBlock"`
	ServerCapabilities                ServerCapabilities               `json:"ServerCapabilities"`
	ServerNotification                ClientNotification               `json:"ServerNotification"`
	ServerRequest                     ClientNotification               `json:"ServerRequest"`
	ServerResult                      Result                           `json:"ServerResult"`
	SetLevelRequest                   CallToolRequest                  `json:"SetLevelRequest"`
	SetLevelRequestParams             SetLevelRequestParams            `json:"SetLevelRequestParams"`
	SingleSelectEnumSchema            ClientNotification               `json:"SingleSelectEnumSchema"`
	StringSchema                      StringSchema                     `json:"StringSchema"`
	SubscribeRequest                  CallToolRequest                  `json:"SubscribeRequest"`
	SubscribeRequestParams            ReadResourceRequestParamsClass   `json:"SubscribeRequestParams"`
	Task                              Task                             `json:"Task"`
	TaskAugmentedRequestParams        TaskAugmentedRequestParams       `json:"TaskAugmentedRequestParams"`
	TaskMetadata                      TaskMetadata                     `json:"TaskMetadata"`
	TaskStatus                        LoggingLevel                     `json:"TaskStatus"`
	TaskStatusNotification            CallToolRequest                  `json:"TaskStatusNotification"`
	TaskStatusNotificationParams      CancelTaskResult                 `json:"TaskStatusNotificationParams"`
	TextContent                       EmbeddedResource                 `json:"TextContent"`
	TextResourceContents              ResourceContents                 `json:"TextResourceContents"`
	TitledMultiSelectEnumSchema       TitledMultiSelectEnumSchema      `json:"TitledMultiSelectEnumSchema"`
	TitledSingleSelectEnumSchema      TitledSingleSelectEnumSchema     `json:"TitledSingleSelectEnumSchema"`
	Tool                              Tool                             `json:"Tool"`
	ToolAnnotations                   ToolAnnotations                  `json:"ToolAnnotations"`
	ToolChoice                        ToolChoice                       `json:"ToolChoice"`
	ToolExecution                     ToolExecution                    `json:"ToolExecution"`
	ToolListChangedNotification       CallToolRequest                  `json:"ToolListChangedNotification"`
	ToolResultContent                 ToolResultContent                `json:"ToolResultContent"`
	ToolUseContent                    ToolUseContent                   `json:"ToolUseContent"`
	URLElicitationRequiredError       URLElicitationRequiredError      `json:"URLElicitationRequiredError"`
	UnsubscribeRequest                CallToolRequest                  `json:"UnsubscribeRequest"`
	UnsubscribeRequestParams          ReadResourceRequestParamsClass   `json:"UnsubscribeRequestParams"`
	UntitledMultiSelectEnumSchema     UntitledMultiSelectEnumSchema    `json:"UntitledMultiSelectEnumSchema"`
	UntitledSingleSelectEnumSchema    TitledSingleSelectEnumSchema     `json:"UntitledSingleSelectEnumSchema"`
}
