package v20250618

type Definitions struct {
	Annotations                     Annotations                 `json:"Annotations"`
	AudioContent                    Content                     `json:"AudioContent"`
	BaseMetadata                    BaseMetadata                `json:"BaseMetadata"`
	BlobResourceContents            ResourceContents            `json:"BlobResourceContents"`
	BooleanSchema                   BooleanSchema               `json:"BooleanSchema"`
	CallToolRequest                 CallToolRequest             `json:"CallToolRequest"`
	CallToolResult                  CallToolResult              `json:"CallToolResult"`
	CancelledNotification           CancelledNotification       `json:"CancelledNotification"`
	ClientCapabilities              ClientCapabilities          `json:"ClientCapabilities"`
	ClientNotification              ClientNotification          `json:"ClientNotification"`
	ClientRequest                   ClientNotification          `json:"ClientRequest"`
	ClientResult                    ClientNotification          `json:"ClientResult"`
	CompleteRequest                 CompleteRequest             `json:"CompleteRequest"`
	CompleteResult                  CompleteResult              `json:"CompleteResult"`
	ContentBlock                    ClientNotification          `json:"ContentBlock"`
	CreateMessageRequest            CreateMessageRequest        `json:"CreateMessageRequest"`
	CreateMessageResult             CreateMessageResult         `json:"CreateMessageResult"`
	Cursor                          Cursor                      `json:"Cursor"`
	ElicitRequest                   ElicitRequest               `json:"ElicitRequest"`
	ElicitResult                    ElicitResult                `json:"ElicitResult"`
	EmbeddedResource                EmbeddedResource            `json:"EmbeddedResource"`
	EmptyResult                     EmptyResult                 `json:"EmptyResult"`
	EnumSchema                      EnumSchema                  `json:"EnumSchema"`
	GetPromptRequest                GetPromptRequest            `json:"GetPromptRequest"`
	GetPromptResult                 GetPromptResult             `json:"GetPromptResult"`
	ImageContent                    Content                     `json:"ImageContent"`
	Implementation                  Implementation              `json:"Implementation"`
	InitializeRequest               InitializeRequest           `json:"InitializeRequest"`
	InitializeResult                InitializeResult            `json:"InitializeResult"`
	InitializedNotification         InitializedNotification     `json:"InitializedNotification"`
	JSONRPCError                    JSONRPCError                `json:"JSONRPCError"`
	JSONRPCMessage                  JsonrpcMessage              `json:"JSONRPCMessage"`
	JSONRPCNotification             JSONRPCNotification         `json:"JSONRPCNotification"`
	JSONRPCRequest                  JSONRPCRequest              `json:"JSONRPCRequest"`
	JSONRPCResponse                 JSONRPCResponse             `json:"JSONRPCResponse"`
	ListPromptsRequest              ListSRequest                `json:"ListPromptsRequest"`
	ListPromptsResult               ListPromptsResult           `json:"ListPromptsResult"`
	ListResourceTemplatesRequest    ListSRequest                `json:"ListResourceTemplatesRequest"`
	ListResourceTemplatesResult     ListResourceTemplatesResult `json:"ListResourceTemplatesResult"`
	ListResourcesRequest            ListSRequest                `json:"ListResourcesRequest"`
	ListResourcesResult             ListResourcesResult         `json:"ListResourcesResult"`
	ListRootsRequest                InitializedNotification     `json:"ListRootsRequest"`
	ListRootsResult                 ListRootsResult             `json:"ListRootsResult"`
	ListToolsRequest                ListSRequest                `json:"ListToolsRequest"`
	ListToolsResult                 ListToolsResult             `json:"ListToolsResult"`
	LoggingLevel                    LoggingLevel                `json:"LoggingLevel"`
	LoggingMessageNotification      LoggingMessageNotification  `json:"LoggingMessageNotification"`
	ModelHint                       ModelHint                   `json:"ModelHint"`
	ModelPreferences                ModelPreferences            `json:"ModelPreferences"`
	Notification                    Notification                `json:"Notification"`
	NumberSchema                    NumberSchema                `json:"NumberSchema"`
	PaginatedRequest                PaginatedRequest            `json:"PaginatedRequest"`
	PaginatedResult                 PaginatedResult             `json:"PaginatedResult"`
	PingRequest                     InitializedNotification     `json:"PingRequest"`
	PrimitiveSchemaDefinition       JsonrpcMessage              `json:"PrimitiveSchemaDefinition"`
	ProgressNotification            ProgressNotification        `json:"ProgressNotification"`
	ProgressToken                   ProgressToken               `json:"ProgressToken"`
	Prompt                          Prompt                      `json:"Prompt"`
	PromptArgument                  PromptArgument              `json:"PromptArgument"`
	PromptListChangedNotification   InitializedNotification     `json:"PromptListChangedNotification"`
	PromptMessage                   PromptMessage               `json:"PromptMessage"`
	PromptReference                 PromptReference             `json:"PromptReference"`
	ReadResourceRequest             ReadResourceRequest         `json:"ReadResourceRequest"`
	ReadResourceResult              ReadResourceResult          `json:"ReadResourceResult"`
	Request                         Notification                `json:"Request"`
	RequestID                       ProgressToken               `json:"RequestId"`
	Resource                        Resource                    `json:"Resource"`
	ResourceContents                ResourceContentsClass       `json:"ResourceContents"`
	ResourceLink                    Resource                    `json:"ResourceLink"`
	ResourceListChangedNotification InitializedNotification     `json:"ResourceListChangedNotification"`
	ResourceTemplate                Resource                    `json:"ResourceTemplate"`
	ResourceTemplateReference       ResourceTemplateReference   `json:"ResourceTemplateReference"`
	ResourceUpdatedNotification     ReadResourceRequest         `json:"ResourceUpdatedNotification"`
	Result                          Result                      `json:"Result"`
	Role                            LoggingLevel                `json:"Role"`
	Root                            Root                        `json:"Root"`
	RootsListChangedNotification    InitializedNotification     `json:"RootsListChangedNotification"`
	SamplingMessage                 SamplingMessage             `json:"SamplingMessage"`
	ServerCapabilities              ServerCapabilities          `json:"ServerCapabilities"`
	ServerNotification              ClientNotification          `json:"ServerNotification"`
	ServerRequest                   ClientNotification          `json:"ServerRequest"`
	ServerResult                    ClientNotification          `json:"ServerResult"`
	SetLevelRequest                 SetLevelRequest             `json:"SetLevelRequest"`
	StringSchema                    StringSchema                `json:"StringSchema"`
	SubscribeRequest                ReadResourceRequest         `json:"SubscribeRequest"`
	TextContent                     EmbeddedResource            `json:"TextContent"`
	TextResourceContents            ResourceContents            `json:"TextResourceContents"`
	Tool                            Tool                        `json:"Tool"`
	ToolAnnotations                 ToolAnnotations             `json:"ToolAnnotations"`
	ToolListChangedNotification     InitializedNotification     `json:"ToolListChangedNotification"`
	UnsubscribeRequest              ReadResourceRequest         `json:"UnsubscribeRequest"`
}
